version: '3'

services:
  app:
    container_name: stock-hunter
    ports:
      - 192.168.0.194:3000:3000
    build:
      context: .
      dockerfile: Dockerfile
    restart: on-failure

  # db:
  #   container_name: stock-hunter-db
  #   image: postgres
  #   environment:
  #     - POSTGRES_USER=root
  #     - POSTGRES_PASSWORD=root
  #     - POSTGRES_DB=stock-hunter
  #   ports:
  #     - 5432:5432
  #   restart: on-failure
